using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyCompanyAttribute("IDERA, Inc.")]
[assembly: AssemblyProductAttribute("SQL Compliance Manager")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2004-2021 IDERA, Inc., All Rights Reserved.")]
[assembly: AssemblyVersionAttribute("5.9.0.0")]
[assembly: AssemblyFileVersion("5.9.0.0")]
